channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask-labextension
  - jupyterhub-singleuser=1.3.0  # match JupyterHub deployment version
  - jupyterlab-h5web
  - nbgitpuller
  - nbserverproxy
  - nbconvert-webpdf
  - nodejs
  - notebook
  - pip  # mamba warns us to explicitly list this dependency
  - voila
